export const SET_TASKS = 'SET_TASKS'
export const SET_TASKS_NULL = 'SET_TASKS_NULL'
export const NETWORK_CONNECTION_ERROR = 'NETWORK_CONNECTION_ERROR'
export const SET_ERROR_NULL = 'SET_ERROR_NULL'
export const TOGGLE_INPUT_BOX = 'TOGGLE_INPUT_BOX'

